# Generated by Django 3.0 on 2020-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='konten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('subjudul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('waktu', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buat-Konten',
            },
        ),
    ]
