# Generated by Django 3.0 on 2020-04-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0002_pesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='jml',
            field=models.IntegerField(default=0),
        ),
    ]
