# Generated by Django 3.0 on 2020-04-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0003_pesan_jml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField(default=0)),
                ('insight', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Buat-Barang',
            },
        ),
    ]
