# Generated by Django 3.0 on 2020-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0004_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='stok',
            field=models.CharField(choices=[('1', 'Stok Ada'), ('2', 'Stok Kosong'), ('3', 'Stok Sedikit')], default='1', max_length=13),
        ),
    ]
