# Generated by Django 3.0 on 2020-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='waktu',
            field=models.TimeField(auto_now=True),
        ),
    ]
