# Generated by Django 3.0 on 2020-04-26 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0008_auto_20200426_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='waktu',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2020, 4, 26, 16, 4, 51, 566241, tzinfo=utc)),
        ),
    ]
