# Generated by Django 3.0 on 2020-04-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0009_auto_20200426_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='waktu',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2020, 4, 26, 23, 5, 48, 850862)),
        ),
    ]
