# Generated by Django 3.0 on 2020-04-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0010_auto_20200426_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='waktu',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
