# Generated by Django 3.0 on 2020-04-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0012_pesan_warna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='stok',
            field=models.CharField(choices=[('Stok Ada', '1'), ('Stok Kosong', '2'), ('Stok Sedikit', '3')], default='Stok Ada', max_length=13),
        ),
    ]
