# Generated by Django 3.0 on 2020-04-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0013_auto_20200427_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='stok',
            field=models.CharField(choices=[('1', 'Stok Ada'), ('2', 'Stok Kosong'), ('3', 'Stok Sedikit')], default='Stok Ada', max_length=13),
        ),
    ]
