# Generated by Django 3.0 on 2020-04-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0016_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='sight',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
