# Generated by Django 3.0 on 2020-04-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0017_desc_sight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='sight',
        ),
    ]
