# Generated by Django 3.0 on 2020-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0019_desc_sight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesan',
            old_name='kec',
            new_name='kel',
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='neg',
        ),
    ]
