# Generated by Django 3.0 on 2020-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0021_auto_20200428_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='kd_pos',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
