# Generated by Django 3.0 on 2020-04-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokka', '0022_pesan_kd_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesan',
            old_name='jml',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='pesan',
            old_name='kd_pos',
            new_name='kode_pos',
        ),
        migrations.RenameField(
            model_name='pesan',
            old_name='hp',
            new_name='telepon',
        ),
    ]
